import type { InstructorListing } from '@/types';

export const MOCK_INSTRUCTORS: InstructorListing[] = [
  {
    id: '1',
    userId: 'user1',
    username: 'jan-kowalski',
    fullName: 'Jan Kowalski',
    bio: 'Certyfikowany trener personalny z 8-letnim doświadczeniem. Specjalizuję się w treningach siłowych i budowaniu masy mięśniowej. Pomagam osiągnąć cele fitness poprzez indywidualne podejście i motywację.',
    tagline: 'Certyfikowany trener siłowy • 8+ lat doświadczenia',
    specializations: ['personal-training', 'nutrition-wellness'],
    primarySpecialization: 'personal-training',
    subcategories: ['strength-training', 'sports-nutrition'],
    location: 'Warszawa, Polska',
    city: 'Warszawa',
    hourlyRate: 150,
    photoUrl: 'https://images.unsplash.com/photo-1567013127542-490d757e51fc?w=400&h=400&fit=crop',
    verified: true,
    yearsExperience: 8,
    availability: 'both',
    languages: ['pl', 'en'],
    gallery: [],
    videoUrl: null,
    createdAt: '2024-01-15T10:00:00Z',
    updatedAt: '2024-03-20T14:30:00Z',
    averageRating: 4.9,
    reviewCount: 47,
  },
  {
    id: '2',
    userId: 'user2',
    username: 'anna-nowak',
    fullName: 'Anna Nowak',
    bio: 'Instruktorka jogi z 6-letnim doświadczeniem. Prowadzę zajęcia hatha yoga, vinyasa i medytacji. Pomagam w redukcji stresu i poprawie elastyczności ciała.',
    tagline: 'Instruktorka jogi • Mindfulness & Wellness',
    specializations: ['yoga-mindfulness'],
    primarySpecialization: 'yoga-mindfulness',
    subcategories: ['hatha-yoga', 'vinyasa-yoga', 'meditation'],
    location: 'Kraków, Polska',
    city: 'Kraków',
    hourlyRate: 120,
    photoUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=400&h=400&fit=crop',
    verified: true,
    yearsExperience: 6,
    availability: 'online',
    languages: ['pl', 'en'],
    gallery: [],
    videoUrl: null,
    createdAt: '2024-02-01T09:00:00Z',
    updatedAt: '2024-03-18T11:20:00Z',
    averageRating: 5.0,
    reviewCount: 32,
  },
  {
    id: '3',
    userId: 'user3',
    username: 'piotr-wisniewski',
    fullName: 'Piotr Wiśniewski',
    bio: 'Trener boksu olimpijskiego i MMA. 12 lat doświadczenia w sportach walki. Przygotowuję zawodników do walk oraz prowadzę treningi dla początkujących.',
    tagline: 'Trener sportów walki • Box & MMA',
    specializations: ['combat-sports'],
    primarySpecialization: 'combat-sports',
    subcategories: ['boxing', 'mma', 'kickboxing'],
    location: 'Gdańsk, Polska',
    city: 'Gdańsk',
    hourlyRate: 180,
    photoUrl: 'https://images.unsplash.com/photo-1633332755192-727a05c4013d?w=400&h=400&fit=crop',
    verified: true,
    yearsExperience: 12,
    availability: 'in-person',
    languages: ['pl'],
    gallery: [],
    videoUrl: null,
    createdAt: '2024-01-10T08:00:00Z',
    updatedAt: '2024-03-22T16:45:00Z',
    averageRating: 4.8,
    reviewCount: 65,
  },
  {
    id: '4',
    userId: 'user4',
    username: 'maria-dabrowska',
    fullName: 'Maria Dąbrowska',
    bio: 'Dietetyk kliniczny i trener wellness. Pomagam w zdrowym odchudzaniu i budowaniu zdrowych nawyków żywieniowych. Indywidualne plany żywieniowe.',
    tagline: 'Dietetyk kliniczny • Plany żywieniowe',
    specializations: ['nutrition-wellness'],
    primarySpecialization: 'nutrition-wellness',
    subcategories: ['sports-nutrition', 'weight-loss'],
    location: 'Wrocław, Polska',
    city: 'Wrocław',
    hourlyRate: 140,
    photoUrl: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=400&h=400&fit=crop',
    verified: false,
    yearsExperience: 5,
    availability: 'both',
    languages: ['pl', 'en'],
    gallery: [],
    videoUrl: null,
    createdAt: '2024-02-20T12:00:00Z',
    updatedAt: '2024-03-19T10:15:00Z',
    averageRating: 4.7,
    reviewCount: 28,
  },
  {
    id: '5',
    userId: 'user5',
    username: 'tomasz-lewandowski',
    fullName: 'Tomasz Lewandowski',
    bio: 'Instruktor tańca towarzyskiego i latino. 10 lat doświadczenia w nauczaniu par i singli. Przygotowuję do turniejów tanecznych.',
    tagline: 'Instruktor tańca • Salsa & Latino',
    specializations: ['dance'],
    primarySpecialization: 'dance',
    subcategories: ['salsa'],
    location: 'Poznań, Polska',
    city: 'Poznań',
    hourlyRate: 100,
    photoUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400&h=400&fit=crop',
    verified: true,
    yearsExperience: 10,
    availability: 'in-person',
    languages: ['pl', 'en', 'es'],
    gallery: [],
    videoUrl: null,
    createdAt: '2024-01-25T14:00:00Z',
    updatedAt: '2024-03-21T09:30:00Z',
    averageRating: 4.9,
    reviewCount: 41,
  },
  {
    id: '6',
    userId: 'user6',
    username: 'katarzyna-zielinska',
    fullName: 'Katarzyna Zielińska',
    bio: 'Trenerka biegania i triathlonu. Przygotowuję do maratonów, półmaratonów i zawodów triatlonowych. Plany treningowe dostosowane do poziomu.',
    tagline: 'Trenerka biegania • Marathon & Triathlon',
    specializations: ['cardio-sports'],
    primarySpecialization: 'cardio-sports',
    subcategories: ['running', 'triathlon', 'cycling'],
    location: 'Łódź, Polska',
    city: 'Łódź',
    hourlyRate: 130,
    photoUrl: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=400&h=400&fit=crop',
    verified: true,
    yearsExperience: 7,
    availability: 'both',
    languages: ['pl', 'en'],
    gallery: [],
    videoUrl: null,
    createdAt: '2024-02-10T11:00:00Z',
    updatedAt: '2024-03-20T13:00:00Z',
    averageRating: 4.6,
    reviewCount: 19,
  },
];
